version: 2
enable-beta-ecosystems: true
updates:

  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/."
    schedule:
      interval: "monthly"

