name: Check Pana

on: pull_request

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      min_score: 130
      working_directory: "examples/my_flutter_package"
